"""Global constants for PrivacyCam."""

import os
from pathlib import Path

DEFAULT_WIDTH = 1280
DEFAULT_HEIGHT = 720
DEFAULT_FPS = 30

MIN_CONFIDENCE = 0.1
MAX_CONFIDENCE = 1.0
DEFAULT_CONFIDENCE = 0.5

MAX_QUEUE_SIZE = 2
DEFAULT_DETECTION_INTERVAL = 3

DEFAULT_BLUR_STRENGTH = 31
DEFAULT_EXPANSION = 0.15
DEFAULT_FEATHER = 15
DEFAULT_PIXELATE_BLOCKS = 10
DEFAULT_SOLID_COLOR = (0, 0, 0)

SUPPORTED_DEVICES = ["CPU", "GPU", "NPU", "AUTO"]
DEFAULT_DEVICE = "AUTO"

APP_NAME = "PrivacyCam"
APP_VERSION = "0.1.0"

MIN_FACE_SIZE = 20
MAX_FACES = 50

WARMUP_ITERATIONS = 3
DEFAULT_MAX_LOST_FRAMES = 10

LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

CONFIG_DIR = Path.home() / ".privacycam"
MODELS_DIR = CONFIG_DIR / "models"
